### PR TITLE
Add FlushCacheEdges method to client

### PR DESCRIPTION
**Pull request by katrogan**

### CODE REVIEW

**Review by v-fedorov-gh — APPROVED** [review]
Thank you for doing this - looks good. Would mind doing git rebase -i and squishing the two commits together before submitting (just to keep history clean)

**Comment by katrogan** [comment]
done @v-fedorov-gh

**Comment by katrogan** [comment]
@v-fedorov-gh I don't have write permissions to the repo - do you mind merging in the change?

**Comment by v-fedorov-gh** [comment]
Done. Let me republish as well

**Pull request merged**
